# Tensors

In [37]:
from __future__ import print_function
import torch

In [40]:
#Construct a 5x3 matrix, uninitialized:
x = torch.empty(5, 3)
print(x)

tensor([[8.4490e-39, 9.6428e-39, 1.1112e-38],
        [9.5511e-39, 1.0102e-38, 9.6428e-39],
        [1.0286e-38, 1.0653e-38, 4.6837e-39],
        [4.1327e-39, 5.1429e-39, 9.0918e-39],
        [5.2348e-39, 8.9081e-39, 9.3674e-39]])


In [41]:
#Construct a randomly initialized matrix:
x = torch.rand(5, 3)
print(x)

tensor([[0.0726, 0.4209, 0.1338],
        [0.9175, 0.6118, 0.6107],
        [0.6712, 0.6188, 0.7057],
        [0.4497, 0.9955, 0.2747],
        [0.3120, 0.2267, 0.1618]])


In [42]:
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [44]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [45]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [46]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)  

tensor([[-0.2542,  2.3712,  0.8965],
        [ 0.3244, -0.4759, -0.2674],
        [-0.5275,  0.1508, -0.6692],
        [-1.2141,  1.0373,  0.9036],
        [ 0.3090, -1.9990,  2.4115]])


In [48]:
print(x.size())

torch.Size([5, 3])


In [49]:
# Operations
y = torch.rand(5,3)
print(x + y)

tensor([[ 0.5675,  2.6021,  1.6864],
        [ 1.1589,  0.1825,  0.6605],
        [ 0.3036,  0.2281,  0.1561],
        [-1.1471,  1.3610,  1.7401],
        [ 1.0258, -1.8213,  2.9026]])


In [50]:
print(torch.add(x, y))

tensor([[ 0.5675,  2.6021,  1.6864],
        [ 1.1589,  0.1825,  0.6605],
        [ 0.3036,  0.2281,  0.1561],
        [-1.1471,  1.3610,  1.7401],
        [ 1.0258, -1.8213,  2.9026]])


In [51]:
# Addition: providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.5675,  2.6021,  1.6864],
        [ 1.1589,  0.1825,  0.6605],
        [ 0.3036,  0.2281,  0.1561],
        [-1.1471,  1.3610,  1.7401],
        [ 1.0258, -1.8213,  2.9026]])


In [52]:
# Addition: in place
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.5675,  2.6021,  1.6864],
        [ 1.1589,  0.1825,  0.6605],
        [ 0.3036,  0.2281,  0.1561],
        [-1.1471,  1.3610,  1.7401],
        [ 1.0258, -1.8213,  2.9026]])


In [53]:
print(x[:, 1])

tensor([ 2.3712, -0.4759,  0.1508,  1.0373, -1.9990])


In [55]:
#Resizing: If you want to resize/reshape tensor, you can use torch.view:

x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [57]:
# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2491])
0.24913723766803741


In [60]:
## Numpy Bridge
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [61]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [62]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [63]:
# Converting NumPy Array to Torch Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Cuda Tensors
#Tensors can be moved onto any device using the .to method.

In [67]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [66]:
print(z)

tensor([[0.0511, 0.3209, 0.0453, 0.6937, 0.9065, 0.9392, 0.6385, 0.2996],
        [0.5037, 0.4558, 0.9642, 0.0158, 0.1024, 0.0450, 0.1706, 0.6742]])


In [68]:
print(z.to("cpu", torch.double))

tensor([[0.0511, 0.3209, 0.0453, 0.6937, 0.9065, 0.9392, 0.6385, 0.2996],
        [0.5037, 0.4558, 0.9642, 0.0158, 0.1024, 0.0450, 0.1706, 0.6742]],
       dtype=torch.float64)
