In [4]:
# Import TensorFlow library
import tensorflow as tf

In [5]:
# Create TensorFlow object called tensor 
hello_constant = tf.constant('Hello World!')

In [6]:
hello_constant

<tf.Tensor 'Const:0' shape=() dtype=string>

# Tensorflow Session()

In [7]:
with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(hello_constant) # .decode()
    print(output)

b'Hello World!'


Three typoe of data
- Constant
- Place holder
- Variable

In [8]:
# Check version of the tensorflow
print(tf.__version__)

1.14.0


In [ ]:
The central unit of data in Tensoflow

In [18]:
# Initiate tensorflow constant
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0) # also if tf.float32 impkicitly
print(node1,node2)

Tensor("Const_3:0", shape=(), dtype=float32) Tensor("Const_4:0", shape=(), dtype=float32)


In [19]:
sess = tf.Session()
print(sess.run([node1,node2]))
sess.close()

[3.0, 4.0]


# Example: multiply two constants 

In [16]:
import tensorflow as tf
a = tf.constant(4.0)
b = tf.constant(6.0)
c = a * b
c

<tf.Tensor 'mul_3:0' shape=() dtype=float32>

In [17]:
# evaluate the tensor
sess = tf.Session()
print(sess.run(c))
sess.close()

24.0


# Tensorflow Placeholder
- A "placeholder" is a promise to provide a value later.

In [12]:
# What if you want to use a non-constant? This is where tf.placeholder() and feed_dict come into place

In [13]:
import tensorflow as tf
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

adder_node = a+b
sess = tf.Session()
print(sess.run(adder_node, feed_dict={a:[1,7,6,2,1], b:[3,20,2,4,6]}))

[ 4. 27.  8.  6.  7.]


In [15]:
# Do another calculation
Mult_5 = adder_node * 5
print(sess.run(Mult_5,{a:[[1,2,3],
                         [2,3,4],
                         [3,2,1]],b:[[10,2,3],
                                    [2,3,4],
                                    [3,2,1]]}))

[[55. 20. 30.]
 [20. 30. 40.]
 [30. 20. 10.]]


# TensorFlow Varibale
- Variables allow us to add trainable parameters to a graph
- y = .2 + .3*x

In [20]:
import tensorflow as tf

In [21]:
W1 = tf.Variable([.5], tf.float32)
# important : need to run below code to initialize the Variables()
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(W1))

[0.5]


In [11]:
# Y = b + W*x
W = tf.Variable([.3], tf.float32)
b = tf.Variable([-.9], tf.float32)
x = tf.placeholder(tf.float32)

linear_model = W*x + b
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(linear_model,{x:[1,2,3,4,5,7]}))

[-5.9999996e-01 -2.9999995e-01  5.9604645e-08  3.0000007e-01
  6.0000002e-01  1.2000002e+00]


# Tensorflow Math

In [22]:
x = tf.add(5,2)

In [23]:
y = tf.subtract(10, 4) # 6

In [24]:
z = tf.multiply(2,5)  #10

# Converting data types

In [25]:
# tf.subtract(tf.constant(2.0), tf.constant(1)) # Fails with ValueError: Tensor conversion requested

In [27]:
with tf.Session() as sess:
    print(sess.run(tf.subtract(tf.cast(tf.constant(2.0), tf.int32), tf.constant(1)))) #1

1


In [28]:
# Tensorflow devide

In [29]:
import tensorflow as tf

x = tf.constant(10)
y = tf.constant(2)
z = tf.subtract(tf.divide(x,y), tf.cast(tf.constant(1),tf.float64))

with tf.Session() as sess:
    output = sess.run(z)
    print(output)

4.0


# Activation Functions

In [38]:
# 1 / (1 + exp(-x))
import numpy as np
def sigmoid_(a):
    return 1/(1+np.exp(-a))
#sigmoid_(.3)
a = [1,2,4,0,5,-6,7]
for i in a:
    print(sigmoid_(i))

0.7310585786300049
0.8807970779778823
0.9820137900379085
0.5
0.9933071490757153
0.0024726231566347743
0.9990889488055994


In [42]:
#tanh(a) = (e^a - e^-a)/e^a + e^-a

In [41]:
def tanh_(a):
    return np.tanh(a)
tanh_(.3)
a = [-4, -2, 0,2,4]
for i in a:
    print(tanh_(i))

-0.999329299739067
-0.9640275800758169
0.0
0.9640275800758169
0.999329299739067


In [43]:
def relu_(a):
    return np.maximum(0,a)
#relu_(.3)
a = [-4,-2,2,4]
for i in a:
    print(relu_(i))
    # with tf.Session() as sess:
    #print(sess.run(tf.nn.relu(i)))

0
0
2
4


In [37]:
# Softmax
Scores = [12, 8, .3]
import numpy as np
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x), axis=0)
print(softmax(Scores))
print(sum(softmax(Scores)))

[9.82005792e-01 1.79860635e-02 8.14457845e-06]
1.0


In [47]:
# Sigmoid
import numpy as np
a = [.2, 1, 0, 3, -2]
sigmoid_Activation = tf.sigmoid(a)
tanh_Activation = tf.tanh(a)
relu_Activation = tf.nn.relu(a)
with tf.Session() as sess:
    output1 = sess.run(sigmoid_Activation)
    output2 = sess.run(tanh_Activation)
    output3 = sess.run(relu_Activation)
    print("sigmoid_Activation: ", output1)
    print("tanh_Activation: ", output2)
    print("relu_Activation: ", output3)

sigmoid_Activation:  [0.549834   0.7310586  0.5        0.95257413 0.11920292]
tanh_Activation:  [ 0.19737528  0.7615942   0.          0.9950547  -0.9640276 ]
relu_Activation:  [0.2 1.  0.  3.  0. ]


# One Hot Encoding

In [49]:
a = tf.truncated_normal([2,3])
sess = tf.Session()
sess.run(a)

array([[ 1.5434661 ,  0.4389982 ,  0.3506524 ],
       [-1.5463387 , -0.586604  ,  0.02971934]], dtype=float32)

# Loss Function
- A loss function measures how far apart the current model is from the provided data

In [48]:
import tensorflow as tf
# Loss Function
W = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

linear_model = y * x + b